app = "none"
primary_region = "ewr"

[build]

[env]
  PORT = "3001"
  NODE_ENV = "production"
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
  CHROME_BIN = "/usr/bin/google-chrome"
  PUPPETEER_EXECUTABLE_PATH = "/usr/bin/google-chrome"
  API_TOKEN = "b29bfe548cc2a3e4225effbd54ef0fda"
  UI_TOKENS = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3MzE1Mjc1NTIsIm5iZiI6MTczMTUyNzU1MiwiZXhwIjoxNzYyNjMxNTcyLCJkYXRhIjp7InVpZCI6MzYxNTkxLCJ0b2tlbiI6Ijc4NjdlYzc2NzcwODAyNjcxNWNlNTZjMWJiZDI1N2NkIn19.vXKdWeU8R_xe4gUMBg-hIxkftFogPdZEGtXvAw0IC-Q"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.checks]]
  grace_period = "60s"
  interval = "30s"
  method = "GET"
  timeout = "10s"
  path = "/health"
  protocol = "http"

[deploy]
  strategy = "immediate"
  release_command = "echo 'Deployment started'"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024