# fly.toml app configuration file generated for video-api on 2024-12-19T12:00:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "video-api"
primary_region = "iad"

[build]

[env]
  PORT = "8080"
  NODE_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[mounts]
  source = "video_api_data"
  destination = "/data"

[processes]
  app = "node src/app.js" 